.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. adultchain_qt test_adultchain_qt
clean: FORCE
	$(MAKE) -C .. adultchain_qt_clean test_adultchain_qt_clean
check: FORCE
	$(MAKE) -C .. test_adultchain_qt_check
adultchain-qt adultchain-qt.exe: FORCE
	 $(MAKE) -C .. adultchain_qt
